homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 54
  unit_system: imperial
  time_zone: America/Los_Angeles

  packages: !include_dir_named components/packages
