homeassistant:
  customize: !include_dir_merge_named ../../customizations/entities
  customize_domain: !include_dir_merge_named ../../customizations/domains
  customize_glob: !include_dir_merge_named ../../customizations/globs
