alias: system_upgrade_alert
trigger:
  platform: state
  entity_id: sensor.latest_version
condition:
  - condition: template
    value_template: >-
      {{
        states('sensor.latest_version')
        !=
        states('sensor.current_version')
      }}
action:
  - service: persistent_notification.create
    data_template:
      title: Upgrade time!
      message: >-
        There is a Home Assistant upgrade pending!
        Version {{ states('sensor.latest_version') }} just got released!
      notification_id: hassio_upgrade
